version: "3"
services:
  bot:
    image: 192.168.204.149:5000/bot_image
    build:
        context: ./bot
    container_name: "${BOT}"
    environment:
      - TOKEN=${TOKEN}
      - RM_HOST=${RM_HOST}
      - RM_PORT=${RM_PORT}
      - RM_USER=${RM_USER}
      - RM_PASSWORD=${RM_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
    volumes:
      - pg_logs:/var/log/
    env_file:
     - .env
  db:
    image: 192.168.204.149:5000/db_image
    build: ./db
    container_name: "${DB_HOST}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DB_REPL_USER=${DB_REPL_USER}
      - DB_REPL_PASSWORD=${DB_REPL_PASSWORD}
      - DB_REPL_HOST=${DB_REPL_HOST}.my_network
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
    volumes:
      - pg_logs:/var/log/
    ports:
      - ${DB_PORT}:5432
    env_file:
     - .env
  db_repl:
    image: 192.168.204.149:5000/db_repl_image
    build: ./db_repl
    container_name: "${DB_REPL_HOST}"
    environment:
      - DB_HOST=${DB_HOST}.my_network
      - DB_PORT=${DB_PORT}
      - DB_REPL_HOST=${DB_REPL_HOST}
      - DB_REPL_PORT=${DB_REPL_PORT}
      - DB_REPL_USER=${DB_REPL_USER}
      - DB_REPL_PASSWORD=${DB_REPL_PASSWORD}
    depends_on:
      - db
    ports:
      - ${DB_REPL_PORT}:5434
    env_file:
       - .env
volumes:
  pg_data:
  pg_logs:
networks:
  default:
    name: my_network
    external: true